using System.Text;
using Mono.Cecil;

namespace VssCodex;

/// <summary>Shared markdown helpers: proprietary header banner, anchors, file writing.</summary>
public static class MarkdownWriter
{
    /// <summary>
    /// Standard header stamped on every generated file: source assembly + version, generation note,
    /// and the do-not-commit banner so a stray copy is self-identifying.
    /// </summary>
    public static string Header(string title, string sourceLabel, string genDate)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"# {title}");
        sb.AppendLine();
        sb.AppendLine("> **⚠️ PROPRIETARY — AUTO-GENERATED — DO NOT COMMIT.**  ");
        sb.AppendLine($"> Generated by `vss-codex` on {genDate} from `{sourceLabel}`.  ");
        sb.AppendLine("> Derived from decompiled Vintage Story binaries; lives in the gitignored output");
        sb.AppendLine("> tree. Re-run `vss-codex.ps1` after a VS update.");
        sb.AppendLine();
        return sb.ToString();
    }

    public static string AssemblyLabel(ModuleDefinition m) =>
        $"{m.Assembly.Name.Name}.dll v{m.Assembly.Name.Version}";

    /// <summary>GitHub-style anchor slug for a heading.</summary>
    public static string Slug(string text)
    {
        var sb = new StringBuilder(text.Length);
        foreach (char c in text.ToLowerInvariant())
        {
            if (char.IsLetterOrDigit(c)) sb.Append(c);
            else if (c is ' ' or '-' or '_' or '.') sb.Append('-');
            // drop other punctuation
        }
        return sb.ToString();
    }

    public static void Write(string outDir, string relativePath, string content)
    {
        string full = Path.Combine(outDir, relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);
        File.WriteAllText(full, content);
    }

    /// <summary>Escape the markdown table-cell separator in inline code.</summary>
    public static string EscapePipes(string s) => s.Replace("|", "\\|");
}
