using System.Text;

namespace VssCodex;

/// <summary>
/// Build the mkdocs.yml that drives the browsable site. We do NOT render anything ourselves: this is
/// pure text - a Material theme config plus an ordered nav derived from the generated docs tree. The
/// real MkDocs (Python) reads it, renders the markdown, and produces the static, searchable site.
/// Kept free of any Python/subprocess concern so it is fully unit-testable without MkDocs installed.
/// </summary>
public static class MkDocsConfigGenerator
{
    /// <summary>Render the complete mkdocs.yml for the docs tree at <paramref name="docsDir"/>.</summary>
    public static string BuildYaml(string docsDir, BuildInfo info)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by vss-codex - do not edit; it is rebuilt on every run.");
        sb.AppendLine($"site_name: {Quote($"Vintage Story API - vss-codex ({info.VsVersion})")}");
        sb.AppendLine("docs_dir: docs");
        sb.AppendLine("site_dir: site");
        sb.AppendLine("use_directory_urls: false   # portable links: events.html, not events/");
        sb.AppendLine();
        sb.AppendLine("theme:");
        sb.AppendLine("  name: material");
        sb.AppendLine("  features:");
        // No navigation.instant: it fetches pages over XHR and needs a server; keep links plain.
        foreach (var f in new[]
                 {
                     "navigation.sections", "navigation.indexes", "navigation.top",
                     "search.suggest", "search.highlight", "content.code.copy", "toc.follow",
                 })
            sb.AppendLine($"    - {f}");
        sb.AppendLine();
        sb.AppendLine("plugins:");
        sb.AppendLine("  - search");
        sb.AppendLine();
        sb.AppendLine("markdown_extensions:");
        sb.AppendLine("  - admonition");
        sb.AppendLine("  - tables");
        sb.AppendLine("  - toc:");
        sb.AppendLine("      permalink: true");
        sb.AppendLine("  - pymdownx.highlight");
        sb.AppendLine("  - pymdownx.superfences");
        sb.AppendLine();

        BuildNav(sb, docsDir);
        return sb.ToString();
    }

    private static void BuildNav(StringBuilder sb, string docsDir)
    {
        bool Has(string rel) => File.Exists(Path.Combine(docsDir, rel.Replace('/', Path.DirectorySeparatorChar)));

        string Indent(int depth) => new(' ', depth * 2);
        void Item(int depth, string rel) => sb.AppendLine($"{Indent(depth)}- {Quote(TitleFor(rel))}: {rel}");
        void Section(int depth, string title) => sb.AppendLine($"{Indent(depth)}- {Quote(title)}:");

        sb.AppendLine("nav:");
        if (Has("README.md")) Item(1, "README.md");
        if (Has("entity-simulation.md")) Item(1, "entity-simulation.md");

        // --- API section ---
        var apiPages = Md(docsDir, "generated/api", "INDEX.md", "events.md", "enums.md");
        if (Has("generated/api/INDEX.md") || apiPages.Count > 0)
        {
            Section(1, "API");
            if (Has("generated/api/INDEX.md")) Item(2, "generated/api/INDEX.md");
            foreach (var p in apiPages) Item(2, p);
            if (Has("generated/api/events.md")) Item(2, "generated/api/events.md");
            if (Has("generated/api/enums.md")) Item(2, "generated/api/enums.md");

            var libPages = Md(docsDir, "generated/api/lib", "INDEX.md");
            if (Has("generated/api/lib/INDEX.md") || libPages.Count > 0)
            {
                Section(2, "Engine internals (lib)");
                if (Has("generated/api/lib/INDEX.md")) Item(3, "generated/api/lib/INDEX.md");
                foreach (var p in libPages) Item(3, p);
            }
        }

        // --- Harmony section ---
        var patchable = Md(docsDir, "generated/harmony", "INDEX.md", "high-value-targets.md");
        if (Has("generated/harmony/INDEX.md") || patchable.Count > 0)
        {
            Section(1, "Harmony");
            if (Has("generated/harmony/INDEX.md")) Item(2, "generated/harmony/INDEX.md");
            if (Has("generated/harmony/high-value-targets.md")) Item(2, "generated/harmony/high-value-targets.md");
            foreach (var p in patchable) Item(2, p);
        }

        // --- Version-diff changelogs (present only after a second run against a new VS version) ---
        var changelogs = Md(docsDir, "generated").FindAll(p => Path.GetFileName(p).StartsWith("CHANGELOG-"));
        if (changelogs.Count > 0)
        {
            Section(1, "Version diffs");
            foreach (var p in changelogs) Item(2, p);
        }
    }

    /// <summary>Markdown files directly under <paramref name="subdir"/>, sorted, as docs-relative paths.</summary>
    private static List<string> Md(string docsDir, string subdir, params string[] exclude)
    {
        string dir = Path.Combine(docsDir, subdir.Replace('/', Path.DirectorySeparatorChar));
        if (!Directory.Exists(dir)) return new();
        return Directory.GetFiles(dir, "*.md")
            .Select(f => Path.GetFileName(f)!)
            .Where(n => !exclude.Contains(n))
            .OrderBy(n => n, StringComparer.Ordinal)
            .Select(n => $"{subdir}/{n}")
            .ToList();
    }

    /// <summary>A short, human nav label for a docs-relative markdown path.</summary>
    public static string TitleFor(string relPath)
    {
        string stem = Path.GetFileNameWithoutExtension(relPath);
        return stem switch
        {
            "README" => "Home",
            "INDEX" => "Overview",
            "entity-simulation" => "Entity simulation",
            "events" => "Events",
            "enums" => "Enums",
            "high-value-targets" => "High-value targets",
            _ when stem.StartsWith("patchable-") => "Patchable: " + stem["patchable-".Length..],
            _ when stem.StartsWith("CHANGELOG-") => stem["CHANGELOG-".Length..].Replace("-to-", " -> "),
            _ => stem, // namespace pages keep their dotted name, e.g. Vintagestory.API.Server
        };
    }

    // Single-quoted YAML scalar (safe for ':', '-', parentheses in titles); escape embedded quotes.
    private static string Quote(string s) => "'" + s.Replace("'", "''") + "'";
}
